---
version: "3"
services:
  jenkins:
    container_name: jenkins_master
    image: jenkins/jenkins
    ports:
      - "8080:8080"
    volumes:
      - "/jenkins/master:/var/jenkins_home"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - net
  jenkins-slave:
    container_name: jenkins_slave
    image: jenkins_slave
    build:
      context: jenkins_slave
    volumes:
      - "/jenkins/jenkins_slave/slave_home:/var/jenkins_home"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - net
networks:
  net:
